### ISSUE TITLE
Force update of git status when folder is refreshed

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/files#1161]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
The new integration with `git` is awesome (thanks!) but the status of pushed files/folders is not updated unless `Files` is closed/opened.

**Describe the solution you'd like**
Update the status of the current repo when `F5` is used inside one of its folders.

**Existing work**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeremypw** [comment]
Thanks for the report. You are right - the git status cache is not being cleared when the folder is reloaded.  Should be fixed soon.

**Comment by Gabriel-p** [comment]
The new Files in Horus comes with updated icons for git repos but this minor inconvenience is still present

**Comment by jeremypw** [comment]
@Gabriel-p Apologies, this fell off the radar :disappointed:   I have now pushed a PR that should fix this.
