### ISSUE TITLE
4.4.3 Build fails with both GCC 10 and Clang 10

### ISSUE THREAD

**Issue by alucryd** [elementary/files#1341]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Building 4.4.3 fails for different reasons with GCC 10 and Clang 10. FYI I can "fix" the clang build by temporarily passing `-Wno-return-type`.

### Logs
GCC: https://buildbot.alucryd.xyz/#/builders/213/builds/10/steps/7/logs/stdio
Clang: https://buildbot.alucryd.xyz/#/builders/213/builds/11/steps/7/logs/stdio

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Arch Linux, GCC 10, Clang 10.

**Comment by jeremypw** [comment]
Did the previous release build OK under the same conditions?

**Comment by jeremypw** [comment]
The Clang problem seems to be due to a quirk in the way the Vala compiler handles `return_if_fail` in a void async function.  If this is replaced by a simple `if` clause then the problem goes away.

**Comment by jeremypw** [comment]
@alucryd I think I fixed the CLang10 issue with the linked #1342 but cannot test it.  Are you able to confirm whether that PR fixes that issue.  

The issue with GCC10 has a different cause and should probably have been raised separately so that it can fixed in a separate PR.

**Comment by alucryd** [comment]
@jeremypw This indeed fixes the clang building, thanks!

**Comment by jeremypw** [comment]
Thanks - I'll look into the GCC10 issue.

**Comment by jeremypw** [comment]
@alucryd I have pushed a draft PR (linked) that may fix the GCC 10 build problem - are you able to test it please?

**Comment by alucryd** [comment]
Sure, it still fails to build, here is the error log: https://paste.xinu.at/vXQaHWjlh8gFw8Rc/

**Comment by jeremypw** [comment]
@alucryd  Thanks for trying!.  Seems I have got rid of some errors so I am on the right track.  Hopefully next commits will compete the fix.

**Comment by alucryd** [comment]
@jeremypw did you get around completing your GCC fix? 4.4.4 still fails to build here.

**Comment by jeremypw** [comment]
@alucryd  Sorry - rather forgot about that one.  I'll have another look at it.

**Comment by jeremypw** [comment]
@alucryd  Is 84ee73f sufficient to fix the GCC problem?  If so I'll revert the PR to that point.  It started failing CI after that and I am having trouble identifying and fixing the problem.

**Comment by jeremypw** [comment]
@alucryd Its OK - I have set up a test install with GCC10 (the PR failed to build with GCC10 with just the commit that passed CI unfortunately)

**Comment by alucryd** [comment]
@jeremypw Apologies for the late reply, my free time is scarce these days. Awesome, glad you got a local build running!

**Comment by alucryd** [comment]
Thanks, confirmed 4.5.0 is building on Arch Linux!
