### ISSUE TITLE
new files don't show in folder until the view is refreshed

### ISSUE THREAD

**Issue by janxkoci** [elementary/files#2288]
### What Happened?

I often create files using CLI and such files don't show up in Files until I refresh the folder view. The same situation can also happen when the files are made by other apps than just CLI (e.g. copying in FTP clients, saving office file to new file, etc.).

### Steps to Reproduce

1. Open Files in some folder.
2. Right-click and open the folder in Terminal.
3. Type `touch new_random_file` and confirm with Enter.
4. Bring Files to focus - no new file appeared in current folder yet.
5. Press F5 on your keyboard - the new file appears.

The same issue can also be reproduced by e.g. saving a new file from office suite or text editor.

### Expected Behavior

Files should always show the correct contents of a folder, without a need for refreshing. I recall this was the behaviour some time ago (Hera? Jólnir?).

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
This was supposed to fixed by the latest release, I think.  Just tried your example with Files compiled from `main` and the new file appears in the view immediately whether or not Files is focused.  I'll check with the released version.

**Comment by janxkoci** [comment]
I [thought so](https://github.com/elementary/files/issues/2262#issuecomment-1682068994) too after reading the blog announcement, but I still have the issue.

**Comment by jeremypw** [comment]
Maybe try reinstalling Files and logging out and back in to make sure the new version is running?  I tested just now with "normal" filenames and location (home folder) and with "Show Hidden Files" ON.

**Comment by jeremypw** [comment]
Apologies - I think the commit that fixes it is #2260 which * hasnt* been release yet.  The regression fixed in v6.4.1 in https://github.com/elementary/files/commit/f026bf3afc66a88f72d09d31792afd681bcdedaa was to to do with adding folders not externally adding files.  Sorry for the confusion.

**Comment by jeremypw** [comment]
I guess its about time for another release soon anyway.

**Comment by jeremypw** [comment]
Fixed by #2260

**Comment by janxkoci** [comment]
FWIW I do have version 6.4.1

```
$ io.elementary.files --version
io.elementary.files 6.4.1
```
