### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by Djaler** [elementary/files#515]
`Copy As Link`, `Paste Link`, and ` Pate Link into Folder` is not exists in pot and po files

**Comment by Djaler** [comment]
@tintou can you update po-files too?

**Comment by tintou** [comment]
Done

**Comment by J0Ar** [comment]
This https://github.com/elementary/files/blob/master/src/View/directory_view_popup.ui#L75 string is still missing in german po file. #799
